/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceModelos;

import Herramientas.GraficadorJFrame;
import Modelos.BeggsBrill;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComponent;
/**
 *
 * @author Miguel
 */
public class BeggsBrillJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BeggsBrillJInternalFrame
     */
    
    ArrayList<Double> a = new ArrayList();
    ArrayList<Double> b = new ArrayList();
    private Object[] objetoBeggsBrill;
    private BeggsBrill beggsbrill;
    
    public BeggsBrillJInternalFrame() 
    {
        initComponents();
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    double P1 = 500; //presion corriente arriba
    double Tprom = 120; //Temperatura promedio
    double R; //Relacion gas-aceite producido
    double Yg; //Gravedad especifica del gas
    double Yw; //Gravedad especifica del agua
    double YAPI; //Gravedad del aceite
    double Longitud; //Longitud
    double d; //diametro
    double qL; //Caudal de liquido
    double Dp; //caida de presión supuesta
    double Wcut; //Relacion agua-aceite
    double Bw; //Factor volumetrico de formacion del agua   
    double ug; //Viscosidad del gas
    double uo; //viscosidad del aceite
    double uw; //Viscosidad del agua
    
    private void asignarValores() {
        P1 = Double.parseDouble(P1_jTextField2.getText());
        Tprom = Double.parseDouble(Tprom_jTextField.getText());
        R = Double.parseDouble(R_jTextField.getText());
        Yg = Double.parseDouble(Yg_jTextField.getText());
        Yw = Double.parseDouble(Yw_jTextField.getText());
        YAPI = Double.parseDouble(YAPI_jTextField.getText());
        Longitud = Double.parseDouble(Longitud_jTextField.getText());
        d = Double.parseDouble(d_jTextField.getText());
        qL = Double.parseDouble(qL_jTextField.getText());   
        Dp = Double.parseDouble(Dp_jTextField.getText());   
        Wcut = Double.parseDouble(Wcut_jTextField.getText());  
        Bw = Double.parseDouble(Bw_jTextField.getText());  
        ug = Double.parseDouble(ug_jTextField.getText());  
        uo = Double.parseDouble(uo_jTextField.getText());  
        uw = Double.parseDouble(uw_jTextField.getText());  
    }

    public int[] rango() //Limites del eje y
    {
        int[] rango = new int[2];
        rango[0] = (int) Math.round(b.get(0));
        rango[1] = rango[0];
        for (int i = 1; i < b.size(); i++) {
            if (rango[0] > (int) Math.round(b.get(i))) {
                rango[0] = (int) Math.round(b.get(i));
            }
            if (rango[1] < (int) Math.round(b.get(i))) {
                rango[1] = (int) Math.round(b.get(i));
            }
        }
        return rango;
    }

    public void crearVectores() {
        objetoBeggsBrill = new Object[3];        
        double L = Longitud;
        for (int i = 0; i < 3; i++) {            
            beggsbrill = new BeggsBrill(L, P1, Tprom, R, Yg, Yw, YAPI, d, qL, Dp, Wcut,Bw,ug,uo,uw);           
            a.add(L);
            b.add(500 - beggsbrill.getDp());
            objetoBeggsBrill[i] = (Object) beggsbrill;
            L = L + 1000;    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tprom_jTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        P1_jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        Longitud_jTextField = new javax.swing.JTextField();
        d_jTextField = new javax.swing.JTextField();
        qL_jTextField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jComboBox18 = new javax.swing.JComboBox();
        jComboBox20 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        Wcut_jTextField = new javax.swing.JTextField();
        R_jTextField = new javax.swing.JTextField();
        Yg_jTextField = new javax.swing.JTextField();
        Yw_jTextField = new javax.swing.JTextField();
        YAPI_jTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Dp_jTextField = new javax.swing.JTextField();
        jComboBox14 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Bw_jTextField = new javax.swing.JTextField();
        ug_jTextField = new javax.swing.JTextField();
        uo_jTextField = new javax.swing.JTextField();
        uw_jTextField = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), " Source Properties"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 20, 10));

        jLabel1.setText("Temperature");
        jPanel1.add(jLabel1);

        Tprom_jTextField.setText("120");
        Tprom_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tprom_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(Tprom_jTextField);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F" }));
        jPanel1.add(jComboBox1);

        jLabel2.setText("Pressure");
        jPanel1.add(jLabel2);

        P1_jTextField2.setText("500");
        jPanel1.add(P1_jTextField2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "psia" }));
        jPanel1.add(jComboBox2);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties - Flowline"));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel13.setLayout(new java.awt.GridLayout(7, 1, 0, 15));

        jLabel14.setText("Horizontal Distance");
        jPanel13.add(jLabel14);

        jLabel16.setText("Inner Diameter");
        jPanel13.add(jLabel16);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Liquid Rate" }));
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel13.add(jComboBox12);

        jPanel14.setLayout(new java.awt.GridLayout(7, 1, 15, 15));

        Longitud_jTextField.setText("1000");
        Longitud_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Longitud_jTextFieldActionPerformed(evt);
            }
        });
        jPanel14.add(Longitud_jTextField);

        d_jTextField.setText("4");
        d_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_jTextFieldActionPerformed(evt);
            }
        });
        jPanel14.add(d_jTextField);

        qL_jTextField.setText("2000");
        qL_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qL_jTextFieldActionPerformed(evt);
            }
        });
        jPanel14.add(qL_jTextField);

        jPanel12.setLayout(new java.awt.GridLayout(7, 1, 15, 15));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ft" }));
        jPanel12.add(jComboBox18);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "inches" }));
        jPanel12.add(jComboBox20);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STB/d" }));
        jPanel12.add(jComboBox13);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel5, java.awt.BorderLayout.CENTER);

        jButton1.setText("Resultados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Black Oil Properties"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Stck Tank Properties"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 15, 15));

        jPanel3.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wcut" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox6);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GOR" }));
        jPanel3.add(jComboBox3);

        jLabel3.setText("Gas S.G");
        jPanel3.add(jLabel3);

        jLabel4.setText("Water S.G");
        jPanel3.add(jLabel4);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "API" }));
        jPanel3.add(jComboBox4);

        jPanel2.add(jPanel3);

        jPanel7.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        Wcut_jTextField.setText("0");
        jPanel7.add(Wcut_jTextField);

        R_jTextField.setText("1000");
        jPanel7.add(R_jTextField);

        Yg_jTextField.setText("0.65");
        jPanel7.add(Yg_jTextField);

        Yw_jTextField.setText("1.07");
        jPanel7.add(Yw_jTextField);

        YAPI_jTextField.setText("42");
        jPanel7.add(YAPI_jTextField);

        jPanel2.add(jPanel7);

        jPanel4.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox5);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "scf/STB" }));
        jPanel4.add(jComboBox7);

        jPanel2.add(jPanel4);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Supposed Drop Pressure");

        Dp_jTextField.setText("100");
        Dp_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dp_jTextFieldActionPerformed(evt);
            }
        });

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Psi" }));
        jComboBox14.setToolTipText("");

        jLabel6.setText("Waterl Volumetric Factor ");

        jLabel7.setText("Gas Viscosity");

        jLabel8.setText("Oil Viscosity");

        jLabel9.setText("Water Viscosity");

        Bw_jTextField.setText("1");

        ug_jTextField.setText("0.02");

        uo_jTextField.setText("1");

        uw_jTextField.setText("1");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bl/STB" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cP" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cP" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cP" }));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(uo_jTextField)
                    .addComponent(ug_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(Bw_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dp_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uw_jTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox14, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Dp_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Bw_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ug_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(uo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(uw_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(24, 24, 24))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tprom_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tprom_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tprom_jTextFieldActionPerformed

    private void d_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_jTextFieldActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void qL_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qL_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qL_jTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        asignarValores();
        crearVectores();
        GraficadorJFrame hijobeggsbrill = new GraficadorJFrame();      
        hijobeggsbrill.graficar(a, b, "titulo grafico", rango()); 
        hijobeggsbrill.resultados(objetoBeggsBrill);
        hijobeggsbrill.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Longitud_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Longitud_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Longitud_jTextFieldActionPerformed

    private void Dp_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dp_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dp_jTextFieldActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bw_jTextField;
    private javax.swing.JTextField Dp_jTextField;
    private javax.swing.JTextField Longitud_jTextField;
    private javax.swing.JTextField P1_jTextField2;
    private javax.swing.JTextField R_jTextField;
    private javax.swing.JTextField Tprom_jTextField;
    private javax.swing.JTextField Wcut_jTextField;
    private javax.swing.JTextField YAPI_jTextField;
    private javax.swing.JTextField Yg_jTextField;
    private javax.swing.JTextField Yw_jTextField;
    private javax.swing.JTextField d_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField qL_jTextField;
    private javax.swing.JTextField ug_jTextField;
    private javax.swing.JTextField uo_jTextField;
    private javax.swing.JTextField uw_jTextField;
    // End of variables declaration//GEN-END:variables
}
