/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceModelos;

import Herramientas.GraficadorJFrame;
import Modelos.LockhartMartinelli;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class LockhartMartinelliJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LockhartMartinelliJInternalFrame
     */
    ArrayList<Double> a = new ArrayList();
    ArrayList<Double> b = new ArrayList();
    private Object[] objetoLockartMartinelli;
    private LockhartMartinelli lockhartmartinelli; 
    private JFrame frame;    
    private double P1;
    private double Tprom; 
    private double d; 
    private double WOR; 
    private double L;   
    private double Wcut; 
    private double qL; 
    private double Yw; 
    private double RGL; 
    private double Yg; 
    private double uL; 
    private double ug; 
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    
    public LockhartMartinelliJInternalFrame() {
        initComponents();
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }
    
    private void source()
    {
        Tprom = Double.parseDouble(Tprom_jTextField.getText());
        P1 = Double.parseDouble(P1_jTextField.getText());
    }
    
    private void flowline()
    {
        d = Double.parseDouble(d_jTextField.getText());        
        L = Double.parseDouble(L_jTextField.getText());       
    }
    
    private void general()
    {
        Wcut = Double.parseDouble(Wcut_jTextField.getText());
        RGL = Double.parseDouble(RGL_jTextField.getText());
        Yg = Double.parseDouble(Yg_jTextField.getText());        
        Yw = Double.parseDouble(Yw_jTextField.getText());
        qL = Double.parseDouble(qL_jTextField.getText());        
        uL = Double.parseDouble(uL_jTextField.getText());      
        ug = Double.parseDouble(ug_jTextField.getText());      
    }
    
    public int[] rango() //Limites del eje y
    {
        int[] rango = new int[2];
        rango[0] = (int) Math.round(b.get(0));
        rango[1] = rango[0];
        for (int i = 1; i < b.size(); i++) {
            if (rango[0] > (int) Math.round(b.get(i))) {
                rango[0] = (int) Math.round(b.get(i));
            }
            if (rango[1] < (int) Math.round(b.get(i))) {
                rango[1] = (int) Math.round(b.get(i));
            }
        }
        return rango;
    }

    public void crearVectores() {
        objetoLockartMartinelli = new Object[3];
        double Longitud = L;
        for (int i = 0; i < 3; i++) {
            lockhartmartinelli = new LockhartMartinelli(d, Yw, qL, Longitud, P1, Yg, Tprom, RGL, uL, ug);
            a.add(Longitud);
            b.add(lockhartmartinelli.getDPTg());
            objetoLockartMartinelli[i] = (Object) lockhartmartinelli;
            Longitud = Longitud + 750;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        source_jPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Tprom_jTextField = new javax.swing.JTextField();
        P1_jTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Flowline_jPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        L_jTextField = new javax.swing.JTextField();
        WOR_jTextField = new javax.swing.JTextField();
        d_jTextField = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        Wcut_jTextField = new javax.swing.JTextField();
        RGL_jTextField = new javax.swing.JTextField();
        Yg_jTextField = new javax.swing.JTextField();
        Yw_jTextField = new javax.swing.JTextField();
        jTextField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        qL_jTextField = new javax.swing.JTextField();
        uL_jTextField = new javax.swing.JTextField();
        ug_jTextField = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Properties"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 3, 15, 15));

        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 15, 15));

        jLabel1.setText("Temperature");
        jPanel4.add(jLabel1);

        jLabel2.setText("Pressure");
        jPanel4.add(jLabel2);

        jPanel6.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 15, 15));

        Tprom_jTextField.setText("120");
        Tprom_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tprom_jTextFieldActionPerformed(evt);
            }
        });
        jPanel5.add(Tprom_jTextField);

        P1_jTextField.setText("850");
        jPanel5.add(P1_jTextField);

        jPanel6.add(jPanel5);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 15, 15));

        jLabel3.setText("F");
        jPanel3.add(jLabel3);

        jLabel4.setText("psia");
        jPanel3.add(jLabel4);

        jPanel6.add(jPanel3);

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout source_jPanelLayout = new javax.swing.GroupLayout(source_jPanel);
        source_jPanel.setLayout(source_jPanelLayout);
        source_jPanelLayout.setHorizontalGroup(
            source_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        source_jPanelLayout.setVerticalGroup(
            source_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(source_jPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Properties"));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3, 15, 15));

        jPanel10.setLayout(new java.awt.GridLayout(6, 1, 15, 15));

        jLabel5.setText("Rate of Undulations");
        jPanel10.add(jLabel5);

        jLabel6.setText("Horizontal Distance");
        jPanel10.add(jLabel6);

        jLabel7.setText("Elevation Difference");
        jPanel10.add(jLabel7);

        jLabel8.setText("Inner Diameter");
        jPanel10.add(jLabel8);

        jLabel10.setText("Roughness");
        jPanel10.add(jLabel10);

        jLabel11.setText("Ambient Temperature");
        jPanel10.add(jLabel11);

        jPanel8.add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(6, 1, 15, 15));

        jTextField3.setText("10falta");
        jPanel12.add(jTextField3);

        L_jTextField.setText("1500");
        jPanel12.add(L_jTextField);

        WOR_jTextField.setText("0falta");
        WOR_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WOR_jTextFieldActionPerformed(evt);
            }
        });
        jPanel12.add(WOR_jTextField);

        d_jTextField.setText("2");
        jPanel12.add(d_jTextField);

        jTextField8.setText("0.00falta");
        jPanel12.add(jTextField8);

        jTextField9.setText("60falta");
        jPanel12.add(jTextField9);

        jPanel8.add(jPanel12);

        jPanel11.setLayout(new java.awt.GridLayout(6, 1, 15, 15));

        jLabel13.setText("/1000");
        jPanel11.add(jLabel13);

        jLabel12.setText("ft");
        jPanel11.add(jLabel12);

        jLabel14.setText("ft");
        jPanel11.add(jLabel14);

        jLabel15.setText("inches");
        jPanel11.add(jLabel15);

        jLabel17.setText("inches");
        jPanel11.add(jLabel17);

        jLabel18.setText("F");
        jPanel11.add(jLabel18);

        jPanel8.add(jPanel11);

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(35, 35, 35)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout Flowline_jPanelLayout = new javax.swing.GroupLayout(Flowline_jPanel);
        Flowline_jPanel.setLayout(Flowline_jPanelLayout);
        Flowline_jPanelLayout.setHorizontalGroup(
            Flowline_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Flowline_jPanelLayout.setVerticalGroup(
            Flowline_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Flowline_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pozo"));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal/Flowline.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal/source.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Resultados");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Stock Tank Properties"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Black Oil Properties"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 15, 15));

        jPanel15.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        jLabel19.setText("Wcut");
        jPanel15.add(jLabel19);

        jLabel20.setText("GLR");
        jPanel15.add(jLabel20);

        jLabel21.setText("Gas S.G");
        jPanel15.add(jLabel21);

        jLabel22.setText("Water S.G");
        jPanel15.add(jLabel22);

        jLabel23.setText("API");
        jPanel15.add(jLabel23);

        jPanel2.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        Wcut_jTextField.setText("0.5");
        jPanel16.add(Wcut_jTextField);

        RGL_jTextField.setText("1000");
        jPanel16.add(RGL_jTextField);

        Yg_jTextField.setText("0.65");
        jPanel16.add(Yg_jTextField);

        Yw_jTextField.setText("1.07");
        jPanel16.add(Yw_jTextField);

        jTextField.setText("42falta");
        jPanel16.add(jTextField);

        jPanel2.add(jPanel16);

        jPanel14.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        jLabel24.setText("%");
        jPanel14.add(jLabel24);

        jLabel25.setText("scf/STB");
        jPanel14.add(jLabel25);

        jPanel2.add(jPanel14);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setLayout(new java.awt.GridLayout(1, 3, 15, 15));

        jPanel18.setLayout(new java.awt.GridLayout(3, 1, 15, 15));

        jLabel27.setText("Liquid Rate");
        jPanel18.add(jLabel27);

        jLabel26.setText("Viscosity of the Liquid");
        jPanel18.add(jLabel26);

        jLabel29.setText("Gas Viscosity");
        jPanel18.add(jLabel29);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(3, 1, 15, 15));

        qL_jTextField.setText("2000");
        jPanel19.add(qL_jTextField);

        uL_jTextField.setText("1");
        jPanel19.add(uL_jTextField);

        ug_jTextField.setText("0.015");
        jPanel19.add(ug_jTextField);

        jPanel17.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(3, 1, 15, 15));

        jLabel28.setText("STB/d");
        jPanel20.add(jLabel28);

        jLabel30.setText("cP");
        jPanel20.add(jLabel30);

        jLabel31.setText("cP");
        jPanel20.add(jLabel31);

        jPanel17.add(jPanel20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        frame = new JFrame();
        frame.repaint();
        frame.add(source_jPanel);
        frame.setResizable(false);       
        frame.setBounds(100, 100, source_jPanel.getPreferredSize().width, source_jPanel.getPreferredSize().height+20);    
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tprom_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tprom_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tprom_jTextFieldActionPerformed

    private void WOR_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WOR_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WOR_jTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frame = new JFrame();
        frame.add(Flowline_jPanel);
        frame.setResizable(false);
        //frame.setSize(source_jPanel.getSize());
        frame.setBounds(100, 100, Flowline_jPanel.getPreferredSize().width+8, Flowline_jPanel.getPreferredSize().height+8);        
        frame.setVisible(true);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            flowline();
            frame.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos y utilizar (.) punto para los decimales");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            source();
            frame.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos y utilizar (.) punto para los decimales");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:        
        frame.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            general();
            source();
            flowline();
            crearVectores();
            GraficadorJFrame hijoLockartMartinelli = new GraficadorJFrame();
            hijoLockartMartinelli.graficar(a, b, "titulo grafico", rango());
            hijoLockartMartinelli.tablaLockhartMartinelli(objetoLockartMartinelli);
            hijoLockartMartinelli.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos y utilizar (.) punto para los decimales");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Flowline_jPanel;
    private javax.swing.JTextField L_jTextField;
    private javax.swing.JTextField P1_jTextField;
    private javax.swing.JTextField RGL_jTextField;
    private javax.swing.JTextField Tprom_jTextField;
    private javax.swing.JTextField WOR_jTextField;
    private javax.swing.JTextField Wcut_jTextField;
    private javax.swing.JTextField Yg_jTextField;
    private javax.swing.JTextField Yw_jTextField;
    private javax.swing.JTextField d_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField qL_jTextField;
    private javax.swing.JPanel source_jPanel;
    private javax.swing.JTextField uL_jTextField;
    private javax.swing.JTextField ug_jTextField;
    // End of variables declaration//GEN-END:variables
}
